services:
  mongo:
    image: mongo:latest
    container_name: receipt_mongo
    restart: always
    environment:
      # Initialize root user using .env variables
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      # Variables for mongo-init.sh
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}
      APP_DB_NAME: ${APP_DB_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

volumes:
  mongo_data: